### PR TITLE
Improved doc and setup

### PR DESCRIPTION
**Pull request by pombredanne**
As a follow up to our discussion on #11 here is a pull request that:

1. updates the README doc
2. add docstrings aligned with the update documentation
3. ensure code comment headers are consistent and present 

It may not be 100% correct yet, but I think this is a decent first pass. 
@WojciechMula your feedback is welcomed!

### CODE REVIEW

**Comment by pombredanne** [comment]
Note: the formatted display of the docstrings when calling help() may not be there yet!

**Comment by WojciechMula** [comment]
WOW! Great work, thanks a lot!

**Comment by WojciechMula** [comment]
> Note: the formatted display of the docstrings when calling help() may not be there yet!

Are you going to upgrade also this?

**Comment by pombredanne** [comment]
@WojciechMula you wrote:
> Are you going to upgrade also this?

Yes I will tackle this tomorrow. Doing proper multiline docstrings in C strings requires a bit of fiddling with line returns left and right. I will fix this the hard way: visually reviewing all docs when calling help() on the corresponding object.

Thank you for pulling this in so quickly BTW!

**Comment by pombredanne** [comment]
And I will submit a new PR for the formatting.

**Comment by WojciechMula** [comment]
Great, then we will tag repo.

**Pull request merged**
